spring:
  datasource:
    url: ${MYSQL_C5_URL}
    username: ${MYSQL_C5_USER}
    password: ${MYSQL_C5_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

search-service:
 ribbon:
  listOfServers: http://localhost:8090