security:
  oauth2:
    sso:
      loginPath: /login
    resource:
      userInfoUri: http://localhost:9000/uaa/me
spring:
  datasource:
    url: ${MYSQL_C5_URL}
    username: ${MYSQL_C5_USER}
    password: ${MYSQL_C5_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

