spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        inventoryQ:
          destination: inventoryQ
        checkInQ:
          destination: checkInQ

security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
