spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        inventoryQ:
          destination: inventoryQ
        checkInQ:
          destination: checkInQ

security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user
    client:
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      clientId: book-service
      clientSecret: secret
      scope: server

fares-proxy:
  ribbon:
    listOfServers: localhost:8080,localhost:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG