security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user
    client:
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      checkTokenEndpointUrl: http://localhost:9000/uaa/oauth/check_token
      clientId: checkin-service
      clientSecret: secret
      scope: server


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        checkInQ:
          destination: checkInQ

  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/