spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        checkInQ:
          destination: checkInQ

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/