spring:
  application:
    name: fares-apigateway

security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user

zuul:
  routes:
    fares-apigateway:
      serviceId: fare-service
      path: /api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/