security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      clientId: fares-service
      clientSecret: secret
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:9000/uaa/user


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/