security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user
    client:
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      checkTokenEndpointUrl: http://localhost:9000/uaa/oauth/check_token
      clientId: fares-service
      clientSecret: secret
      scope: server


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org:
      springframework:
        security: DEBUG