spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

originairports:
  shutdown: SEA

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
