spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

originairports:
  shutdown: SEA

security:
  basic:
    enabled: false
security:
  user:
  password:
    12345

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
