spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/brownfield
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

originairports:
  shutdown: SEA


management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
