spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user
    client:
      clientId: search-service
      clientSecret: secret
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

originairports:
  shutdown: SEA

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
