spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  user:
    password: password
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/uaa/user

originairports:
  shutdown: LAX

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5


logging:
  level:
    org:
      springframework:
        security: DEBUG
