spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: ${MYSQL_C5_URL}
    username: ${MYSQL_C5_USER}
    password: ${MYSQL_C5_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

originairports:
  shutdown: NYC


management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
